-- Retrieve details of all events

SELECT 
	* 
FROM 
	Events;

-- Generate a list of all attendees registered in events

SELECT 
    A.Attendee_Name, A.Attendee_Phone, A.Attendee_Email, A.Attendee_City
FROM 
    Attendees A
JOIN 
    Registrations R ON A.Attendee_id = R.Attendee_id;
    
    
 -- Calculate the total number of attendees for each event
 
SELECT 
    E.Event_id, E.Event_Name, E.Event_Location, E.Event_Date, COUNT(R.Attendee_id) AS Total_Attendees
FROM 
    Events E
LEFT JOIN 
    Registrations R ON E.Event_id = R.Event_id
GROUP BY 
	E.Event_id, E.Event_Name, E.Event_Location, E.Event_Date;

-- Calculate total revenue generated by each event
SELECT 
    E.Event_Name, SUM(R.Registration_Amount) AS Total_Revenue
FROM 
    Events E
JOIN 
    Registrations R ON E.Event_id = R.Event_id
GROUP BY 
    E.Event_id, E.Event_Name;